version: '3.9'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5454:5432'
    environment:
      POSTGRES_PASSWORD: ticketing@2024!
      POSTGRES_DB: 'ticketing'
  api:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    command: '/app/scripts/docker/local-run.sh'
    ports:
      - '8080:8080'
      - '9229:9229'
    env_file: .env.development
    volumes:
      - './src:/app/src'
    depends_on:
      - db
